[package]
name = "beautyxt-diagram-service"
version = "0.1.0"
edition.workspace = true
license = "MIT AND Apache-2.0"
publish.workspace = true
rust-version.workspace = true

[lib]
name = "beautyxt_diagram_service"
crate-type = ["cdylib"]

[dependencies]
beautyxt-diagram-core = { path = "../diagram-core" }
beautyxt-illustration-core = { path = "../illustration-core" }
beautyxt-native-service = { path = "../native-service" }
beautyxt-illustration-service = { path = "../illustration-service" }

[lints]
workspace = true
