/* Owns immutable memory-only input prepared for isolated consumers. */
package dev.soupslurpr.beautyxt.ipc

import android.os.ParcelFileDescriptor
import android.system.Os
import android.system.OsConstants
import dev.soupslurpr.beautyxt.document.EditorDocumentSnapshot
import java.io.FileDescriptor
import java.io.IOException
import java.io.OutputStream

private const val INPUT_BUFFER_NAME = "beautyxt-sealed-input"
private const val SNAPSHOT_TIMEOUT_MILLIS = 30_000L

/** Owns one sealed pathname-free input capability and its exact byte count. */
internal class SealedInput private constructor(
    val byteCount: Long,
    private val device: Long,
    private val inode: Long,
    private var reader: ParcelFileDescriptor?
) : AutoCloseable {
    /** Transfers the only sealed input descriptor to one consumer. */
    @Synchronized
    fun takeReader(): ParcelFileDescriptor {
        val descriptor = checkNotNull(reader) { "sealed input is closed" }
        validateAnonymousDescriptor(descriptor, device, inode, byteCount, requireSeals = true)
        Os.lseek(descriptor.fileDescriptor, 0L, OsConstants.SEEK_SET)
        reader = null
        return descriptor
    }

    /** Closes the retained input capability exactly once. */
    @Synchronized
    override fun close() {
        closeQuietly(reader)
        reader = null
    }

    companion object {
        /** Copies one exact bounded byte array into a sealed anonymous input. */
        fun fromBytes(bytes: ByteArray, maxBytes: Long): SealedInput {
            require(bytes.size.toLong() <= maxBytes) { "input exceeds its byte limit" }
            return fromStream(maxBytes) { output -> output.write(bytes) }
        }

        /** Bounds generated bytes while writing directly into an anonymous memory file. */
        fun fromStream(maxBytes: Long, write: (OutputStream) -> Unit): SealedInput {
            require(maxBytes >= 0L) { "input limit must be nonnegative" }
            return createSealed { writer ->
                BoundedOutputStream(
                    ParcelFileDescriptor.AutoCloseOutputStream(writer),
                    maxBytes
                ).use { output ->
                    write(output)
                    output.flush()
                    output.byteCount
                }
            }
        }

        /** Copies a bounded snapshot synchronously so ownership cannot be lost on dispatch. */
        fun fromSnapshot(
            snapshot: EditorDocumentSnapshot,
            expectedBytes: Long,
            maxBytes: Long
        ): SealedInput {
            require(expectedBytes in 0L..maxBytes) { "snapshot exceeds its byte limit" }
            return createSealed { writer ->
                val cancellation = ParcelFileDescriptor.createPipe()
                try {
                    val writtenBytes = snapshot.writeSnapshot(
                        outputRawFileDescriptor = writer.fd,
                        cancellationRawFileDescriptor = cancellation[0].fd,
                        timeoutMillis = SNAPSHOT_TIMEOUT_MILLIS
                    )
                    if (writtenBytes != expectedBytes) {
                        throw IOException("snapshot byte count changed")
                    }
                    writtenBytes
                } finally {
                    closeQuietly(cancellation[1])
                    closeQuietly(cancellation[0])
                }
            }
        }

        /** Creates, fills, seals, and validates one synchronously owned input buffer. */
        private fun createSealed(writeInput: (ParcelFileDescriptor) -> Long): SealedInput {
            var rawDescriptor: FileDescriptor? = null
            var reader: ParcelFileDescriptor? = null
            try {
                rawDescriptor = createAnonymousDescriptor(INPUT_BUFFER_NAME)
                val initialStatus = Os.fstat(rawDescriptor)
                reader = ParcelFileDescriptor.dup(rawDescriptor)
                val byteCount = ParcelFileDescriptor.dup(rawDescriptor).use(writeInput)
                check(byteCount >= 0L) { "input producer returned a negative byte count" }
                sealAnonymousDescriptor(reader)
                validateAnonymousDescriptor(
                    descriptor = reader,
                    expectedDevice = initialStatus.st_dev,
                    expectedInode = initialStatus.st_ino,
                    expectedBytes = byteCount,
                    requireSeals = true
                )
                return SealedInput(
                    byteCount = byteCount,
                    device = initialStatus.st_dev,
                    inode = initialStatus.st_ino,
                    reader = reader
                ).also { reader = null }
            } finally {
                closeQuietly(reader)
                rawDescriptor?.let(::closeRawDescriptor)
            }
        }
    }
}

/** Closes one parcel descriptor without masking the primary outcome. */
private fun closeQuietly(descriptor: ParcelFileDescriptor?) {
    try {
        descriptor?.close()
    } catch (_: IOException) {
        // Preserve the primary preparation outcome.
    }
}
